import time
import sys
from PyQt5 import QtCore,QtGui,QtWidgets
from staff import staff
if __name__ == '__main__':
    app=QtWidgets.QApplication(sys.argv)
    window=QtWidgets.QWidget()
    window.setGeometry(100,150,600,600)
    window.setWindowTitle('Hospital System')
    window.setWindowIcon(QtGui.QIcon(r'C:\Users\pc\Downloads\hos.png'))
    frame = QtWidgets.QFrame(window)
    frame.setFrameShape(frame.StyledPanel)
    frame.setGeometry(70, 70, 450, 450)
    frame.setStyleSheet("background-color: black;border: 8px solid blue;border-radius:20px")
    lbl3=QtWidgets.QLabel("<b>This System is used for The staff</b>",window)
    lbl3.setStyleSheet("color:red;font-size:25px;border:0px")
    lbl3.setGeometry(90,3,410,100)
    lbl1=QtWidgets.QLabel("<u>UserName:</u>",frame)
    lbl1.setStyleSheet("color:white;font-size:15px;border:0px")
    lbl1.setGeometry(75,60,120,30)
    lbl2=QtWidgets.QLabel("<u>Password:</u>",frame)
    lbl2.setStyleSheet("color:white;font-size:15px;border:0px")
    lbl2.setGeometry(75,180,120,30)
    txt_username = QtWidgets.QLineEdit(frame)
    txt_username.setGeometry(105, 90, 200, 30)
    txt_username.setStyleSheet("background-color: white; border: 1px solid blue; border-radius: 10px;")
    txt_password = QtWidgets.QLineEdit(frame)
    txt_password.setGeometry(105, 210, 200, 30)
    txt_password.setStyleSheet("background-color: white; border: 1px solid blue; border-radius: 10px;")
    txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
    btn1=QtWidgets.QPushButton("Sign up",frame)
    btn1.setGeometry(85,300,120,60)
    btn1.setStyleSheet("background-color:white;border: 1px solid blue;border-radius:20px")
    s=staff()
    btn2=QtWidgets.QPushButton("Log in",frame)
    btn2.setStyleSheet("background-color:white;border: 1px solid blue;border-radius:20px")
    btn2.setGeometry(250,300,120,60)
    btn2.clicked.connect(s.login(txt_username.text(),txt_password.text()))
    window.show()
    app.exec_()